# nixpacks.toml
# Tell Railway’s Nixpacks builder to install both Node + Python runtimes
providers = ["...", "node"]

# (optional) pin the Node major version the HubSpot MCP needs
[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_PYTHON_VERSION = "3.11"

# (optional but recommended) make sure the container still starts your Python API
[start]
cmd = "python -m uvicorn agent_py.server:app --host 0.0.0.0 --port $PORT"
